export const FETCH_MONSTERS = "FETCH_MONSTERS"

export const FETCH_ONE_MONSTER = "FETCH_ONE_MONSTER"

export const GET_MONSTERS_BY_CR = "GET_MONSTERS_BY_CR"

export const SEARCH_MONSTER_NAME = "SEARCH_MONSTER_NAME"

export const ADD_TO_ENCOUNTER = "ADD_TO_ENCOUNTER"